config/routes.rb
RainforestMakers::Application.routes.draw do
  get "reviews/show"

  get "reviews/new"

  get "reviews/edit"

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  get "users/new"
  get "users/create"

  resources :products do
    resources :reviews, :except => [:index]
  end

  resources :users, :only => [:new, :create]
  resources :sessions, :only => [:new, :create, :destroy]

  
  root :to => "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :name, :price_in_cents
  
  validates :description, :name, :presence => true
  validates :price_in_cents, :numericality => {:only_integer => true}

  has_many :reviews
  has_many :users :through => :reviews
  def formatted_price
  	price_in_dollars = price_in_cents.to_f / 100
  	sprintf("%.2f", price_in_dollars)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :comment, :product_id, :user_id
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates_presence_of :password, :on => :create

  has_many :reviews
  has_many :products, :through => :reviews	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  
  def current_user
  	@current_user ||= User.find(session[:id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all

  	respond_to do |format|
  		format.html #index.html.erb
  		format.json{render json: @products}
  	end
  end

  def show
  	@product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end

  	respond_to do |format|
  		format.html #index.html.erb
  		format.json{render json: @product}
  	end

  end

  def new
  	@product = Product.new

  	respond_to do |format|
  		format.html #index.html.erb
  		format.json{render json: @product}
  	end

  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(params[:product])

  	respond_to do |format|
  		if @product.save
  			format.html {redirect_to @product, notice: 'Product was successfully created.'}
  			format.html {render json: @product, status: :created, location: @product}
  		else
  			format.html {render action: "new"}
  			format.json {render json: @product.errors, status: :unprocessable_entity}
  		end
	end

  end

  def update
  	@product = Product.find(params[:id])

  	respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy

  	respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

	def photo_params
			params.require(:product).permit(:name, :description, :price_in_cents)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_filter :load_product

  def show
  	@review = Review.find(params[:id])
  end

  def new
  	
  end
  def edit
  	
  end

  def create
  	@review = Review.product.build(params[:review])
  	@review.user_id = current_user.id

  	 # Check out this article on [.build](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel)
    # You could use a longer alternate syntax if it makes more sense to you
    # 
    # @review = Review.new(
    #   :comment    => params[:review][:comment], 
    #   :product_id => @product.id, 
    #   :user_id    => current_user.id
    # )

	if @review.save
		redirect_to product_path, notice: 'Review created successfully'
	else
		render :action => :show
	end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private
  def load_product
  	@product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		redirect_to products_url, :notice => "Signed up!"
  	else
  		render new
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RainforestMakers</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
	<% end %>

	<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
	<% end %>

<%= yield %>

	<p class="userinfp">
		<% if current_user%>
			Signed in as <%= current_user.email %>.
			<%= link_to "log out", session_path("current"), :method => :delete %>
		<% else %>
			<%= link_to "Log in", new_session_path %> or 
			<%= link_to "Sign up", new_user_path %>
		<% end %>
	</p>
</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  
  <% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
      <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>

  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br />
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Eidt Products</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Products List</h1>

<% @products.each do |product| %>

<p><%= product.name %></p>
<p><%= product.description %></p>
<p><%= product.formatted_price %></p>

<%end%>

<%= link_to 'New', new_product_path %>

app/views/products/new.html.erb
<h1>New Products</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% if current_user %>
	
	<h4>New Review</h4>

	<%= form_for([@product, @review]) do |f| %>
		<% if @review.errors.any? %>
			<div id="error_explanation">
				<h2><%= plurazing(@review.errors.count, "error") %>
					prohibited this review from being saved:
				</h2>
				<ul>
					<% @review.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
					<% end %>
				</ul>
			</div>
		<% end %>

		<div class="field">
			<%= f.label :comment %> <br>
			<%= f.text_area :comment %> 
		</div>

		<div class="actions">
			<%= f.submit %>
		</div>
		<% end %>

		<% else %>
			<p>Please <%= link_to "log in, new_session_path" %> to add a review.</p>
		<% end %>

	<h3>Reviews</h3>
	<p>Reviews for <%= @product.name %></p>
	<% @product.reviews.each do |review| %>
		<p>
			<%= review.comment %>
			<br>
			<% if review.user !=nil %>
			<em>by <%= review.user.email %></em>
			Added on: <%= review.created_at %>
			<% end %>
		</p>
	<% end %>

<p>Name: <%= @product.name %></p>
<p>Description: <%= @product.description %></p>
<p>Price: <%= @product.formatted_price %></p>

<%= link_to 'Back to Home', products_path %>
<%= link_to 'New', new_product_path %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
	<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for message in @user.errors.full_messages %>
			<li><%= message %></li>
			<% end %>
		</ul>
	</div>
	<% end %>

	<div class="field">
		<%= f.label :email %><br/>
		<%= f.text_field :email %><br/>
	</div>

	<div class="field">
		<%= f.label :password %><br/>
		<%= f.password_field :password %><br/>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br/>
		<%= f.password_field :password_confirmation %><br/>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

	<% end %>